version: "3"

services:
  app:
    build: .
    env_file: ./.env
    ports:
      - 8080:8080
    networks:
      - internal
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - internal
volumes:
  mongodata:
networks:
  internal:
    driver: bridge