version: "3"

services:
  frontend:
    image: mlyk1234/combot-frontend:latest
    container_name: frontend
    env_file: ./.env
    ports: 
    - 3000:3000
    networks: 
    - internal
    volumes:
      - ./frontend/build:/usr/share/nginx/html/;
  app:
    container_name: backend
    build: .
    env_file: ./.env
    ports:
      - 8080:8080
    networks:
      - internal
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - internal
volumes:
  mongodata:
networks:
  internal:
    driver: bridge
